/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.util.Date;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Poruka;
import model.User;
import operacije.Operacije;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Acer
 */
public class KlijentskaForma extends javax.swing.JDialog {
    private User ulogovaniKorisnik = null;

    public User getUlogovaniKorisnik() {
        return ulogovaniKorisnik;
    }

    public void setUlogovaniKorisnik(User ulogovaniKorisnik) {
        this.ulogovaniKorisnik = ulogovaniKorisnik;
    }
      
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(java.awt.Frame parent, boolean modal, User u) {
        super(parent, modal);
        initComponents();
        this.ulogovaniKorisnik = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPoruka = new javax.swing.JTextArea();
        btnPosaljiPoruku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("poruka: ");

        txtPoruka.setColumns(20);
        txtPoruka.setRows(5);
        jScrollPane1.setViewportView(txtPoruka);

        btnPosaljiPoruku.setText("Posalji poruku");
        btnPosaljiPoruku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiPorukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPosaljiPoruku, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPosaljiPoruku, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosaljiPorukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiPorukuActionPerformed
        // TODO add your handling code here:
        String txtPoruke = txtPoruka.getText();
        System.out.println(txtPoruka);
        if(txtPoruke.length()>200){
            JOptionPane.showMessageDialog(null,"Text poruke je maximalno 200 karaktera","Informacija",JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            KlijentskiZahtev kz = new KlijentskiZahtev();
            Poruka p = new Poruka();
            p.setPosiljalac(ulogovaniKorisnik);
            System.out.println("ULOGOVANI KORISNIK ID: "+ulogovaniKorisnik.getUserId());
            p.setDatum(new Date());
            p.setPrimalac(null);
            p.setTekstPoruke(txtPoruke);
            kz.setParametar(p);
            kz.setOperacija(Operacije.POSALJI_SVIMA);
            Komunikacija.getInstance().posaljiZahtev(kz);
            //Komunikacija.getInstance().primiOdgovor();
        }
    }//GEN-LAST:event_btnPosaljiPorukuActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosaljiPoruku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPoruka;
    // End of variables declaration//GEN-END:variables
}
